module.exports = {
  iconMap: {
    'glyphicon glyphicon-asterisk': 'bi-asterisk',
    'glyphicon glyphicon-plus': 'bi-plus',
    'glyphicon glyphicon-euro': 'bi-currency-euro',
    'glyphicon glyphicon-eur': 'bi-currency-euro',
    'glyphicon glyphicon-minus': 'bi-minus',
    'glyphicon glyphicon-cloud': 'bi-cloud-fill',
    'glyphicon glyphicon-envelope': 'bi-envelope-fill',
    'glyphicon glyphicon-pencil': 'bi-pencil-fill',
    'glyphicon glyphicon-glass': 'fas fa-glass-martini',
    'glyphicon glyphicon-music': 'bi-music-note-beamed',
    'glyphicon glyphicon-search': 'bi-search',
    'glyphicon glyphicon-heart': 'fas fa-heart',
    'glyphicon glyphicon-star': 'bi-star-fill',
    'glyphicon glyphicon-star-empty': 'bi-star',
    'glyphicon glyphicon-user': 'bi-person-fill',
    'glyphicon glyphicon-film': 'bi-film',
    'glyphicon glyphicon-th-large': 'bi-grid-fill',
    'glyphicon glyphicon-th': 'bi-grid-3x3-gap-fill',
    'glyphicon glyphicon-th-list': 'fas fa-th-list',
    'glyphicon glyphicon-ok': 'bi-check',
    'glyphicon glyphicon-remove': 'bi-x',
    'glyphicon glyphicon-zoom-in': 'bi-zoom-in',
    'glyphicon glyphicon-zoom-out': 'bi-zoom-out',
    'glyphicon glyphicon-off': 'fas fa-power-off',
    'glyphicon glyphicon-signal': 'bi-bar-chart-fill',
    'glyphicon glyphicon-cog': 'fas fa-cog',
    'glyphicon glyphicon-trash': 'bi-trash-fill',
    'glyphicon glyphicon-home': 'fas fa-home',
    'glyphicon glyphicon-file': 'bi-file-earmark',
    'glyphicon glyphicon-time': 'bi-clock',
    'glyphicon glyphicon-road': 'fas fa-road',
    'glyphicon glyphicon-download-alt': 'bi-download',
    'glyphicon glyphicon-download': 'bi-arrow-down-circle',
    'glyphicon glyphicon-upload': 'bi-arrow-up-circle',
    'glyphicon glyphicon-inbox': 'bi-inbox-fill',
    'glyphicon glyphicon-play-circle': 'bi-play-circle',
    'glyphicon glyphicon-repeat': 'fas fa-redo',
    'glyphicon glyphicon-refresh': 'fas fa-sync',
    'glyphicon glyphicon-list-alt': 'bi-card-list',
    'glyphicon glyphicon-lock': 'bi-lock-fill',
    'glyphicon glyphicon-flag': 'bi-flag-fill',
    'glyphicon glyphicon-headphones': 'bi-headphones',
    'glyphicon glyphicon-volume-off': 'bi-volume-mute-fill',
    'glyphicon glyphicon-volume-down': 'bi-volume-down-fill',
    'glyphicon glyphicon-volume-up': 'bi-volume-up-fill',
    'glyphicon glyphicon-qrcode': 'fas fa-qrcode',
    'glyphicon glyphicon-barcode': 'bi-upc',
    'glyphicon glyphicon-tag': 'bi-tag-fill',
    'glyphicon glyphicon-tags': 'bi-tags-fill',
    'glyphicon glyphicon-book': 'fas fa-book',
    'glyphicon glyphicon-bookmark': 'bi-bookmark-fill',
    'glyphicon glyphicon-print': 'bi-printer-fill',
    'glyphicon glyphicon-camera': 'bi-camera-fill',
    'glyphicon glyphicon-font': 'fas fa-font',
    'glyphicon glyphicon-bold': 'fas fa-bold',
    'glyphicon glyphicon-italic': 'fas fa-italic',
    'glyphicon glyphicon-text-height': 'fas fa-text-height',
    'glyphicon glyphicon-text-width': 'fas fa-text-width',
    'glyphicon glyphicon-align-left': 'bi-text-left',
    'glyphicon glyphicon-align-center': 'bi-text-center',
    'glyphicon glyphicon-align-right': 'bi-text-right',
    'glyphicon glyphicon-align-justify': 'bi-justify',
    'glyphicon glyphicon-list': 'bi-list-ul',
    'glyphicon glyphicon-indent-left': 'bi-text-indent-left',
    'glyphicon glyphicon-indent-right': 'bi-text-indent-right',
    'glyphicon glyphicon-facetime-video': 'bi-camera-video-fill',
    'glyphicon glyphicon-picture': 'bi-image',
    'glyphicon glyphicon-map-marker': 'bi-geo-alt-fill',
    'glyphicon glyphicon-adjust': 'bi-circle-half',
    'glyphicon glyphicon-tint': 'bi-droplet-fill',
    'glyphicon glyphicon-edit': 'bi-pencil-square',
    'glyphicon glyphicon-share': 'bi-share',
    'glyphicon glyphicon-check': 'bi-check2-square',
    'glyphicon glyphicon-move': 'bi-arrows-move',
    'glyphicon glyphicon-step-backward': 'fas fa-fast-backward',
    'glyphicon glyphicon-fast-backward': 'fas fa-step-backward',
    'glyphicon glyphicon-backward': 'fas fa-backward',
    'glyphicon glyphicon-play': 'bi-play-fill',
    'glyphicon glyphicon-pause': 'bi-pause-fill',
    'glyphicon glyphicon-stop': 'bi-stop-fill',
    'glyphicon glyphicon-forward': 'fas fa-forward',
    'glyphicon glyphicon-fast-forward': 'fas fa-step-forward',
    'glyphicon glyphicon-step-forward': 'fas fa-fast-forward',
    'glyphicon glyphicon-eject': 'bi-eject-fill',
    'glyphicon glyphicon-chevron-left': 'bi-chevron-left',
    'glyphicon glyphicon-chevron-right': 'bi-chevron-right',
    'glyphicon glyphicon-plus-sign': 'bi-plus-circle-fill',
    'glyphicon glyphicon-minus-sign': 'bi-minus-circle-fill',
    'glyphicon glyphicon-remove-sign': 'bi-x-circle-fill',
    'glyphicon glyphicon-ok-sign': 'bi-check-circle-fill',
    'glyphicon glyphicon-question-sign': 'bi-question-circle-fill',
    'glyphicon glyphicon-info-sign': 'bi-info-circle-fill',
    'glyphicon glyphicon-screenshot': 'fas fa-crosshairs',
    'glyphicon glyphicon-remove-circle': 'bi-x-circle',
    'glyphicon glyphicon-ok-circle': 'bi-check-circle',
    'glyphicon glyphicon-ban-circle': 'bi-slash-circle',
    'glyphicon glyphicon-arrow-left': 'bi-arrow-left',
    'glyphicon glyphicon-arrow-right': 'bi-arrow-right',
    'glyphicon glyphicon-arrow-up': 'bi-arrow-up',
    'glyphicon glyphicon-arrow-down': 'bi-arrow-down',
    'glyphicon glyphicon-share-alt': 'bi-share-fill',
    'glyphicon glyphicon-resize-full': 'bi-arrows-angle-expand',
    'glyphicon glyphicon-resize-small': 'bi-arrows-angle-contract',
    'glyphicon glyphicon-exclamation-sign': 'bi-exclamation-circle-fill',
    'glyphicon glyphicon-gift': 'bi-gift-fill',
    'glyphicon glyphicon-leaf': 'fas fa-leaf',
    'glyphicon glyphicon-fire': 'fas fa-fire',
    'glyphicon glyphicon-eye-open': 'bi-eye-fill',
    'glyphicon glyphicon-eye-close': 'bi-eye-slash-fill',
    'glyphicon glyphicon-warning-sign': 'bi-exclamation-triangle',
    'glyphicon glyphicon-plane': 'fas fa-plane',
    'glyphicon glyphicon-calendar': 'bi-calendar2-week-fill',
    'glyphicon glyphicon-random': 'bi-shuffle',
    'glyphicon glyphicon-comment': 'bi-chat-left-fill',
    'glyphicon glyphicon-magnet': 'fas fa-magnet',
    'glyphicon glyphicon-chevron-up': 'bi-chevron-up',
    'glyphicon glyphicon-chevron-down': 'bi-chevron-down',
    'glyphicon glyphicon-retweet': 'fas fa-retweet',
    'glyphicon glyphicon-shopping-cart': 'bi-cart-fill',
    'glyphicon glyphicon-folder-close': 'fas fa-folder',
    'glyphicon glyphicon-folder-open': 'fas fa-folder-open',
    'glyphicon glyphicon-resize-vertical': 'fas fa-arrows-alt-v',
    'glyphicon glyphicon-resize-horizontal': 'fas fa-arrows-alt-h',
    'glyphicon glyphicon-hdd': 'bi-hdd-fill',
    'glyphicon glyphicon-bullhorn': 'bi-megaphone-fill',
    'glyphicon glyphicon-bell': 'bi-bell',
    'glyphicon glyphicon-certificate': 'fas fa-certificate',
    'glyphicon glyphicon-thumbs-up': 'bi-hand-thumbs-up',
    'glyphicon glyphicon-thumbs-down': 'bi-hand-thumbs-down',
    'glyphicon glyphicon-hand-right': 'far fa-hand-point-right',
    'glyphicon glyphicon-hand-left': 'far fa-hand-point-left',
    'glyphicon glyphicon-hand-up': 'far fa-hand-point-up',
    'glyphicon glyphicon-hand-down': 'far fa-hand-point-down',
    'glyphicon glyphicon-circle-arrow-right': 'bi-arrow-right-circle-fill',
    'glyphicon glyphicon-circle-arrow-left': 'bi-arrow-left-circle-fill',
    'glyphicon glyphicon-circle-arrow-up': 'bi-arrow-up-circle-fill',
    'glyphicon glyphicon-circle-arrow-down': 'bi-arrow-down-circle-fill',
    'glyphicon glyphicon-globe': 'fas fa-globe-americas',
    'glyphicon glyphicon-wrench': 'bi-wrench',
    'glyphicon glyphicon-tasks': 'bi-list-task',
    'glyphicon glyphicon-filter': 'bi-funnel-fill',
    'glyphicon glyphicon-briefcase': 'bi-briefcase-fill',
    'glyphicon glyphicon-fullscreen': 'bi-arrows-fullscreen',
    'glyphicon glyphicon-dashboard': 'bi-speedometer',
    'glyphicon glyphicon-paperclip': 'bi-paperclip',
    'glyphicon glyphicon-heart-empty': 'far fa-heart',
    'glyphicon glyphicon-link': 'bi-link-45deg',
    'glyphicon glyphicon-phone': 'bi-phone',
    'glyphicon glyphicon-pushpin': 'bi-pin-angle-fill',
    'glyphicon glyphicon-usd': 'bi-currency-dollar',
    'glyphicon glyphicon-gbp': 'bi-currency-pound',
    'glyphicon glyphicon-sort': 'bi-arrow-down-up',
    'glyphicon glyphicon-sort-by-alphabet': 'bi-sort-alpha-down',
    'glyphicon glyphicon-sort-by-alphabet-alt': 'bi-sort-alpha-down-alt',
    'glyphicon glyphicon-sort-by-order': 'bi-sort-numeric-down',
    'glyphicon glyphicon-sort-by-order-alt': 'bi-sort-numeric-down-alt',
    'glyphicon glyphicon-sort-by-attributes': 'bi-sort-down-alt',
    'glyphicon glyphicon-sort-by-attributes-alt': 'bi-sort-down',
    'glyphicon glyphicon-unchecked': 'bi-square',
    'glyphicon glyphicon-expand': 'bi-caret-right-square',
    'glyphicon glyphicon-collapse-down': 'bi-caret-down-square',
    'glyphicon glyphicon-collapse-up': 'bi-caret-up-square',
    'glyphicon glyphicon-log-in': 'bi-box-arrow-in-right',
    'glyphicon glyphicon-flash': 'bi-lightning-charge-fill',
    'glyphicon glyphicon-log-out': 'bi-box-arrow-right',
    'glyphicon glyphicon-new-window': 'bi-box-arrow-up-right',
    'glyphicon glyphicon-record': 'bi-record-circle',
    'glyphicon glyphicon-save': 'bi-download',
    'glyphicon glyphicon-open': 'bi-upload',
    'glyphicon glyphicon-saved': 'bi-check',
    'glyphicon glyphicon-import': 'bi-download',
    'glyphicon glyphicon-export': 'bi-upload',
    'glyphicon glyphicon-send': 'fas fa-paper-plane',
    'glyphicon glyphicon-floppy-disk': 'fas fa-save',
    'glyphicon glyphicon-floppy-saved': 'bi-check',
    'glyphicon glyphicon-floppy-remove': 'bi-x',
    'glyphicon glyphicon-floppy-save': 'bi-download',
    'glyphicon glyphicon-floppy-open': 'bi-upload',
    'glyphicon glyphicon-credit-card': 'bi-credit-card-fill',
    'glyphicon glyphicon-transfer': 'bi-arrow-left-right',
    'glyphicon glyphicon-cutlery': 'fas fa-utensils',
    'glyphicon glyphicon-header': 'fas fa-heading',
    'glyphicon glyphicon-compressed': 'fas fa-file-archive',
    'glyphicon glyphicon-earphone': 'bi-telephone-fill',
    'glyphicon glyphicon-phone-alt': 'bi-telephone-fill',
    'glyphicon glyphicon-tower': 'fas fa-chess-rook',
    'glyphicon glyphicon-stats': 'bi-bar-chart-fill',
    'glyphicon glyphicon-sd-video': '',
    'glyphicon glyphicon-hd-video': 'bi-badge-hd-fill',
    'glyphicon glyphicon-subtitles': 'bi-badge-cc-fill',
    'glyphicon glyphicon-sound-stereo': '',
    'glyphicon glyphicon-sound-dolby': '',
    'glyphicon glyphicon-sound-5-1': '',
    'glyphicon glyphicon-sound-6-1': '',
    'glyphicon glyphicon-sound-7-1': '',
    'glyphicon glyphicon-copyright-mark': 'far fa-copyright',
    'glyphicon glyphicon-registration-mark': 'far fa-registered',
    'glyphicon glyphicon-cloud-download': 'bi-cloud-arrow-down-fill',
    'glyphicon glyphicon-cloud-upload': 'bi-cloud-arrow-up-fill',
    'glyphicon glyphicon-tree-conifer': 'bi-tree-fill',
    'glyphicon glyphicon-tree-deciduous': 'bi-tree-fill',
    'glyphicon glyphicon-cd': 'bi-disc-fill',
    'glyphicon glyphicon-save-file': 'bi-file-earmark-arrow-down',
    'glyphicon glyphicon-open-file': 'bi-file-earmark-arrow-up',
    'glyphicon glyphicon-level-up': 'fas fa-level-up-alt',
    'glyphicon glyphicon-copy': 'fas fa-clipboard',
    'glyphicon glyphicon-paste': 'fas fa-paste',
    'glyphicon glyphicon-alert': 'bi-exclamation-triangle-fill',
    'glyphicon glyphicon-equalizer': 'bi-sliders',
    'glyphicon glyphicon-king': 'fas fa-chess-king',
    'glyphicon glyphicon-queen': 'fas fa-chess-queen',
    'glyphicon glyphicon-pawn': 'fas fa-chess-pawn',
    'glyphicon glyphicon-bishop': 'fas fa-chess-bishop',
    'glyphicon glyphicon-knight': 'fas fa-chess-knight',
    'glyphicon glyphicon-baby-formula': 'fas fa-baby',
    'glyphicon glyphicon-tent': 'fas fa-campground',
    'glyphicon glyphicon-blackboard': 'fas fa-chalkboard',
    'glyphicon glyphicon-bed': 'fas fa-bed',
    'glyphicon glyphicon-apple': 'fas fa-apple-alt',
    'glyphicon glyphicon-erase': 'bi-eraser-fill',
    'glyphicon glyphicon-hourglass': 'bi-hourglass',
    'glyphicon glyphicon-lamp': 'bi-lamp-fill',
    'glyphicon glyphicon-duplicate': 'fas fa-copy',
    'glyphicon glyphicon-piggy-bank': 'bi-piggy-bank-fill',
    'glyphicon glyphicon-scissors': 'bi-scissors',
    'glyphicon glyphicon-bitcoin': 'bi-currency-bitcoin',
    'glyphicon glyphicon-btc': 'bi-currency-bitcoin',
    'glyphicon glyphicon-xbt': 'bi-currency-bitcoin',
    'glyphicon glyphicon-yen': 'bi-currency-yen',
    'glyphicon glyphicon-jpy': 'bi-currency-yen',
    'glyphicon glyphicon-ruble': 'fas fa-ruble-sign',
    'glyphicon glyphicon-rub': 'fas fa-ruble-sign',
    'glyphicon glyphicon-scale': 'fas fa-weight',
    'glyphicon glyphicon-ice-lolly': 'fas fa-ice-cream',
    'glyphicon glyphicon-ice-lolly-tasted': 'fas fa-ice-cream',
    'glyphicon glyphicon-education': 'fas fa-graduation-cap',
    'glyphicon glyphicon-option-horizontal': 'bi-three-dots',
    'glyphicon glyphicon-option-vertical': 'bi-three-dots-vertical',
    'glyphicon glyphicon-menu-hamburger': 'bi-list',
    'glyphicon glyphicon-modal-window': '',
    'glyphicon glyphicon-oil': '',
    'glyphicon glyphicon-grain': '',
    'glyphicon glyphicon-sunglasses': 'bi-sunglasses',
    'glyphicon glyphicon-text-size': '',
    'glyphicon glyphicon-text-color': '',
    'glyphicon glyphicon-text-background': '',
    'glyphicon glyphicon-object-align-top': 'bi-align-top',
    'glyphicon glyphicon-object-align-bottom': 'bi-align-bottom',
    'glyphicon glyphicon-object-align-horizontal': 'bi-align-middle',
    'glyphicon glyphicon-object-align-left': 'bi-align-left',
    'glyphicon glyphicon-object-align-vertical': 'bi-align-center',
    'glyphicon glyphicon-object-align-right': 'bi-align-right',
    'glyphicon glyphicon-triangle-right': 'bi-caret-down-right',
    'glyphicon glyphicon-triangle-left': 'bi-caret-down-left',
    'glyphicon glyphicon-triangle-bottom': 'bi-caret-down-fill',
    'glyphicon glyphicon-triangle-top': 'bi-caret-down-up',
    'glyphicon glyphicon-console': 'fas fa-terminal',
    'glyphicon glyphicon-superscript': 'fas fa-superscript',
    'glyphicon glyphicon-subscript': 'fas fa-subscript',
    'glyphicon glyphicon-menu-left': 'bi-chevron-left',
    'glyphicon glyphicon-menu-right': 'bi-chevron-right',
    'glyphicon glyphicon-menu-down': 'bi-chevron-down',
    'glyphicon glyphicon-menu-up': 'bi-chevron-up'
  },
  mapIcon (icon) {
    if (Object.keys(this.iconMap).includes(icon)) {
      return this.iconMap[icon] !== '' ? this.iconMap[icon] : icon
    } else return icon
  }
}
